In [ ]:
#!pip install xgboost

In [2]:
## import the libraries 
import pandas as pd

In [3]:
data = pd.read_csv("churn_data.csv")

In [4]:
data

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
0,128,25,265.1,197.4,244.7,10.0,1,0,0,1,110,45.07,99,16.78,91,11.01,3,2.70
1,107,26,161.6,195.5,254.4,13.7,1,0,0,1,123,27.47,103,16.62,103,11.45,3,3.70
2,137,0,243.4,121.2,162.6,12.2,0,0,0,0,114,41.38,110,10.30,104,7.32,5,3.29
3,84,0,299.4,61.9,196.9,6.6,2,0,1,0,71,50.90,88,5.26,89,8.86,7,1.78
4,75,0,166.7,148.3,186.9,10.1,3,0,1,0,113,28.34,122,12.61,121,8.41,3,2.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,36,156.2,215.5,279.1,9.9,2,0,0,1,77,26.55,126,18.32,83,12.56,6,2.67
3329,68,0,231.1,153.4,191.3,9.6,3,0,0,0,57,39.29,55,13.04,123,8.61,4,2.59
3330,28,0,180.8,288.8,191.9,14.1,2,0,0,0,109,30.74,58,24.55,91,8.64,6,3.81
3331,184,0,213.8,159.6,139.2,5.0,2,0,1,0,105,36.35,84,13.57,137,6.26,10,1.35
3332,74,25,234.4,265.9,241.4,13.7,0,0,0,1,113,39.85,82,22.60,77,10.86,4,3.70

In [5]:
## Data exploration 
type(data)

pandas.core.frame.DataFrame

In [6]:
data.notnull()

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3329,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3330,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3331,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3332,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [7]:
data.isnull()

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3329,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3330,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3331,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3332,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
data.isnull().sum()

Account Length    0
VMail Message     0
Day Mins          0
Eve Mins          0
Night Mins        0
Intl Mins         0
CustServ Calls    0
Churn             0
Int'l Plan        0
VMail Plan        0
Day Calls         0
Day Charge        0
Eve Calls         0
Eve Charge        0
Night Calls       0
Night Charge      0
Intl Calls        0
Intl Charge       0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Account Length  3333 non-null   int64
 1   VMail Message   3333 non-null   int64
 2   Day Mins        3333 non-null   float64
 3   Eve Mins        3333 non-null   float64
 4   Night Mins      3333 non-null   float64
 5   Intl Mins       3333 non-null   float64
 6   CustServ Calls  3333 non-null   int64
 7   Churn           3333 non-null   int64
 8   Int'l Plan      3333 non-null   int64
 9   VMail Plan      3333 non-null   int64
 10  Day Calls       3333 non-null   int64
 11  Day Charge      3333 non-null   float64
 12  Eve Calls       3333 non-null   int64
 13  Eve Charge      3333 non-null   float64
 14  Night Calls     3333 non-null   int64
 15  Night Charge    3333 non-null   float64
 16  Intl Calls      3333 non-null   int64
 17  Intl Charge     3333 non-null   float64
dtypes: float64(8), int64(10)
memory usage: 468.8 KB

In [10]:
data.describe()

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,8.099010,179.775098,200.980348,200.872037,10.237294,1.562856,0.144914,0.096910,0.276628,100.435644,30.562307,100.114311,17.083540,100.107711,9.039325,4.479448,2.764581
std,39.822106,13.688365,54.467389,50.713844,50.573847,2.791840,1.315491,0.352067,0.295879,0.447398,20.069084,9.259435,19.922625,4.310668,19.568609,2.275873,2.461214,0.753773
min,1.000000,0.000000,0.000000,0.000000,23.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,33.000000,1.040000,0.000000,0.000000
25%,74.000000,0.000000,143.700000,166.600000,167.000000,8.500000,1.000000,0.000000,0.000000,0.000000,87.000000,24.430000,87.000000,14.160000,87.000000,7.520000,3.000000,2.300000
50%,101.000000,0.000000,179.400000,201.400000,201.200000,10.300000,1.000000,0.000000,0.000000,0.000000,101.000000,30.500000,100.000000,17.120000,100.000000,9.050000,4.000000,2.780000
75%,127.000000,20.000000,216.400000,235.300000,235.300000,12.100000,2.000000,0.000000,0.000000,1.000000,114.000000,36.790000,114.000000,20.000000,113.000000,10.590000,6.000000,3.270000
max,243.000000,51.000000,350.800000,363.700000,395.000000,20.000000,9.000000,1.000000,1.000000,1.000000,165.000000,59.640000,170.000000,30.910000,175.000000,17.770000,20.000000,5.400000

In [25]:
import pandas as pd
import numpy as nm

In [12]:
import csv

In [13]:
xgboost_params = { 
   "objective": "binary:logistic",
   "booster": "gbtree",
   "eval_metric": "auc",
   "eta": 0.01, # 0.06, #0.01,
   #"min_child_weight": 240,
   "subsample": 0.75,
   "colsample_bytree": 0.68,
   "max_depth": 7
}

In [14]:
data = pd.read_csv("churn_data.csv")

In [15]:
data.head(5)

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
0,128,25,265.1,197.4,244.7,10.0,1,0,0,1,110,45.07,99,16.78,91,11.01,3,2.70
1,107,26,161.6,195.5,254.4,13.7,1,0,0,1,123,27.47,103,16.62,103,11.45,3,3.70
2,137,0,243.4,121.2,162.6,12.2,0,0,0,0,114,41.38,110,10.30,104,7.32,5,3.29
3,84,0,299.4,61.9,196.9,6.6,2,0,1,0,71,50.90,88,5.26,89,8.86,7,1.78
4,75,0,166.7,148.3,186.9,10.1,3,0,1,0,113,28.34,122,12.61,121,8.41,3,2.73

In [16]:
data.shape

(3333, 18)

In [17]:
train = data[:2000]

In [18]:
train

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
0,128,25,265.1,197.4,244.7,10.0,1,0,0,1,110,45.07,99,16.78,91,11.01,3,2.70
1,107,26,161.6,195.5,254.4,13.7,1,0,0,1,123,27.47,103,16.62,103,11.45,3,3.70
2,137,0,243.4,121.2,162.6,12.2,0,0,0,0,114,41.38,110,10.30,104,7.32,5,3.29
3,84,0,299.4,61.9,196.9,6.6,2,0,1,0,71,50.90,88,5.26,89,8.86,7,1.78
4,75,0,166.7,148.3,186.9,10.1,3,0,1,0,113,28.34,122,12.61,121,8.41,3,2.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,118,35,256.3,258.1,215.5,11.7,1,0,0,1,119,43.57,91,21.94,130,9.70,1,3.16
1996,89,0,179.7,299.8,185.3,7.6,1,0,0,0,128,30.55,92,25.48,120,8.34,3,2.05
1997,93,0,266.0,130.1,165.8,13.1,3,0,0,0,120,45.22,84,11.06,63,7.46,6,3.54
1998,85,0,96.7,193.8,171.7,9.7,2,0,0,0,97,16.44,95,16.47,88,7.73,3,2.62
1999,160,0,82.7,194.6,159.0,10.9,0,0,0,0,116,14.06,95,16.54,54,7.15,9,2.94

In [19]:
test = data[2000:]

In [20]:
test

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Churn,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
2000,28,0,168.2,161.7,192.4,10.1,3,0,0,0,87,28.59,92,13.74,112,8.66,3,2.73
2001,73,0,286.4,178.2,214.2,10.7,1,1,0,0,109,48.69,67,15.15,152,9.64,14,2.89
2002,156,0,174.3,186.6,258.2,12.9,3,0,0,0,95,29.63,128,15.86,105,11.62,5,3.48
2003,33,0,190.6,161.7,189.9,13.0,1,0,1,0,100,32.40,104,13.74,136,8.55,6,3.51
2004,77,0,175.5,205.1,245.2,17.8,4,0,0,0,86,29.84,78,17.43,100,11.03,3,4.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,36,156.2,215.5,279.1,9.9,2,0,0,1,77,26.55,126,18.32,83,12.56,6,2.67
3329,68,0,231.1,153.4,191.3,9.6,3,0,0,0,57,39.29,55,13.04,123,8.61,4,2.59
3330,28,0,180.8,288.8,191.9,14.1,2,0,0,0,109,30.74,58,24.55,91,8.64,6,3.81
3331,184,0,213.8,159.6,139.2,5.0,2,0,1,0,105,36.35,84,13.57,137,6.26,10,1.35
3332,74,25,234.4,265.9,241.4,13.7,0,0,0,1,113,39.85,82,22.60,77,10.86,4,3.70

In [21]:
eval = test[:]

In [22]:
target = train["Churn"]

In [23]:
train = train.drop(["Churn"], axis=1)

In [24]:
test = test.drop(["Churn"], axis=1)

In [29]:
train

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Int'l Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge
0,128,25,265.1,197.4,244.7,10.0,1,0,1,110,45.07,99,16.78,91,11.01,3,2.70
1,107,26,161.6,195.5,254.4,13.7,1,0,1,123,27.47,103,16.62,103,11.45,3,3.70
2,137,0,243.4,121.2,162.6,12.2,0,0,0,114,41.38,110,10.30,104,7.32,5,3.29
3,84,0,299.4,61.9,196.9,6.6,2,1,0,71,50.90,88,5.26,89,8.86,7,1.78
4,75,0,166.7,148.3,186.9,10.1,3,1,0,113,28.34,122,12.61,121,8.41,3,2.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,118,35,256.3,258.1,215.5,11.7,1,0,1,119,43.57,91,21.94,130,9.70,1,3.16
1996,89,0,179.7,299.8,185.3,7.6,1,0,0,128,30.55,92,25.48,120,8.34,3,2.05
1997,93,0,266.0,130.1,165.8,13.1,3,0,0,120,45.22,84,11.06,63,7.46,6,3.54
1998,85,0,96.7,193.8,171.7,9.7,2,0,0,97,16.44,95,16.47,88,7.73,3,2.62
1999,160,0,82.7,194.6,159.0,10.9,0,0,0,116,14.06,95,16.54,54,7.15,9,2.94

In [27]:
train.values

array([[128.  ,  25.  , 265.1 , ...,  11.01,   3.  ,   2.7 ],
       [107.  ,  26.  , 161.6 , ...,  11.45,   3.  ,   3.7 ],
       [137.  ,   0.  , 243.4 , ...,   7.32,   5.  ,   3.29],
       ...,
       [ 93.  ,   0.  , 266.  , ...,   7.46,   6.  ,   3.54],
       [ 85.  ,   0.  ,  96.7 , ...,   7.73,   3.  ,   2.62],
       [160.  ,   0.  ,  82.7 , ...,   7.15,   9.  ,   2.94]])

In [43]:
from sklearn.ensemble import GradientBoostingClassifier

In [44]:
model = GradientBoostingClassifier(n_estimators=500, learning_rate=0.1, max_depth=3, random_state=0)
model.fit(train, target)
pred = model.predict(test)

In [45]:
pred

array([0, 1, 0, ..., 0, 0, 0])

In [48]:
eval["Churn"]

2000    0
2001    1
2002    0
2003    0
2004    0
       ..
3328    0
3329    0
3330    0
3331    0
3332    0
Name: Churn, Length: 1333, dtype: int64

In [49]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(eval['Churn'], pred)
print(ac)

0.9452363090772693

In [50]:
results_GBC = pd.DataFrame(pred)
results_GBC.to_csv("results_GBC.csv")

In [6]:
import pickle
file_name='Churn_file.pkl'
f = open(file_name,'wb')
pickle.dump(churn_data.csv,f)
f.close()

NameError: name 'churn_data' is not defined